
CREATE DATABASE be01;
CREATE USER 'be01@'@'localhost' IDENTIFIED BY 'pass123';
GRANT ALL PRIVILEGES ON 'be01'.* TO 'be01'@'localhost';
FLUSH PRIVILEGES;

TRUNCATE TABLE account CASCADE;

ALTER TABLE accounts MODIFY COLUMN email VARCHAR(64);
ALTER TABLE accounts MODIFY COLUMN password VARCHAR(128);
ALTER TABLE accounts MODIFY COLUMN name VARCHAR(128);
ALTER TABLE accounts MODIFY COLUMN id_account VARCHAR(128);
ALTER TABLE accounts ADD UNIQUE KEY(email);
